<?php
namespace Drupal\spotify_lookup\Form;
use Drupal\Core\Form\ConfigFormBase;
use Drupal\Core\Form\FormStateInterface;

class SpotifyLookupForm extends ConfigFormBase {

  /**
   * @inheritDoc
   */
  protected function getEditableConfigNames(){
    return ['spotify_lookup.api_keys'];
  }

  /**
   * @inheritDoc
   */
  public function getFormId(){
    return 'spotify_api_form';
  }

  public function buildForm(array $form, FormStateInterface $form_state) {
    $config = $this->config('spotify_lookup.api_keys');

    $form['spotifyLookup'] = [
      '#type' => 'textfield',
      '#title' => $this->t('spotifyLookup'),
      '#description' => $this->t('Please provide the salutation you would like to use'),
      '#default_value' => $config->get('spotifyLookup')
    ];
    $form['API-Key'] = [
      '#type' => 'textfield',
      '#title' => $this->t('API-Key'),
      '#description' => $this->t('Provide the API key'),
      '#default_value' => $config->get('API-Key')
    ];
    return parent::buildForm($form, $form_state);
  }

  public function submitForm(array &$form, FormStateInterface $form_state){
    $this->config('spotify_lookup.api_keys')
      ->set('spotifyLookup', $form_state->getValue('spotifyLookup'))
      ->save();

    parent::submitForm($form, $form_state); // TODO: Change the autogenerated stub
  }

}


