<?php
namespace Drupal\spotify_lookup\Form;
use Drupal\Core\Form\ConfigFormBase;
use Drupal\Core\Form\FormStateInterface;

class SpotifyLookupForm extends ConfigFormBase {

  /**
   * @inheritDoc
   */
  protected function getEditableConfigNames(){
    return ['spotify_lookup.api_keys'];
  }

  /**
   * @inheritDoc
   */
  public function getFormId(){
    return 'spotify_api_form';
  }

  public function buildForm(array $form, FormStateInterface $form_state) {
    $config = $this->config('spotify_lookup.api_keys');

    $form['spotifyAPI'] = [
      '#type' => 'textfield',
      '#title' => $this->t('Spotify API'),
      '#description' => $this->t('Provide the API key'),
      '#default_value' => $config->get('spotifyAPI'),
    ];
    $form['spotifySecretAPI'] = [
      '#type' => 'textfield',
      '#title' => $this->t('Spotify Secret API'),
      '#description' => $this->t('Provide the secret API key'),
      '#default_value' => $config->get('spotifySecretAPI')
    ];
    return parent::buildForm($form, $form_state);
  }

  public function submitForm(array &$form, FormStateInterface $form_state){
    \Drupal::state()->setMultiple(['auth' => $form_state->getValue('spotifyAPI'), 'secret' => $form_state->getValue('spotifySecretAPI')]);
    $this->config('spotify_lookup.api_keys');


    parent::submitForm($form, $form_state); // TODO: Change the autogenerated stub
  }

}
